apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mongodb-doorman
  annotations:
    fluxcd.io/automated: "false"
  namespace: supplychain-ns
spec:
  replicaCount: 1
  replicas: 1
  releaseName: mongodb-doorman
  chart:
    path: platforms/r3-corda/charts/mongodb
    git: https://github.com/James-Ronayne/blockchain-automation-framework.git
    ref: local
  values:
    nodeName: mongodb-doorman
    metadata:
      namespace: supplychain-ns
    image:
      containerName: mongo:3.6.6
      imagePullSecret: regcred
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    storage:
      memory: 512Mi
      name: minikubestorageclass
      mountPath: /data/db
      volname: hostvol
    vault:
      address: http://192.168.99.100:8200
      role: vault-role
      authpath: cordadoorman
      secretprefix: doorman/credentials/mongodb
      serviceaccountname: vault-auth
      certsecretprefix: doorman/certs
    service:
      tcp:
          port: 27017
          targetPort: 27017
      type: NodePort
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}
    mongodb:
      username: doorman
    cluster:
      enabled: false